stages:
  - build
  - deploy

build_job:
  stage: build
  image: gradle:7.5-jdk17
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $AWS_EC2_HOST >> ~/.ssh/known_hosts
  script:
    - scp build/libs/my-app.jar $AWS_EC2_USER@$AWS_EC2_HOST:/home/ec2-user/app/
    - ssh $AWS_EC2_USER@$AWS_EC2_HOST 'java -jar /home/ec2-user/app/my-app.jar'
  only:
    - main