stages:
  - build
  - deploy

build_job:
  stage: build
  image: gradle:7.5-jdk17
  script:
    - ./gradlew build

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - scp build/libs/my-app.jar $AWS_EC2_USER@$AWS_EC2_HOST:/home/ec2-user/app/
    - ssh $AWS_EC2_USER@$AWS_EC2_HOST 'java -jar /home/ec2-user/app/my-app.jar'